name: cpp ci/cd-pipeline-project

on:
  push:
    branches: 
      - master
    tags:
      - v1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Compiler installation
        run: |
          sudo apt update
          sudo apt install -y 

      - name: Build project
        run: |
          g++ cppunit_test.cc -o cppunit_test

      - name: runs test
        run: |
          ./cppunit_test --output-on-failure 

  build-docker-image:
    runs-on: ubuntu-latest
    needs: [test]

    steps:


  